#!/bin/sh

ACTIVATED_VENV=""
for ACTIVATE_PATH in venv/bin/activate .venv/bin/activate env/bin/activate ENV/bin/activate woodenv/bin/activate ../woodenv/bin/activate; do
    if [ -f "$ACTIVATE_PATH" ]; then
        . "$ACTIVATE_PATH"
        ACTIVATED_VENV="$ACTIVATE_PATH"
        break
    fi
done

if [ -z "$ACTIVATED_VENV" ]; then
    printf "No virtual environment found (checked: venv, env, woodenv, ../woodenv). Push aborted.\n\n"
    exit 1
fi
printf "Activated Virtual Environment $ACTIVATE_PATH\n\n"

printf "Running checks before push...\n\n"

# git config core.hooksPath .git
# chmod +x .githooks/pre-push

printf "Checking migrations:\n"
python manage.py makemigrations --check
if [ $? -ne 0 ]; then
    printf "Migrations need to be made. Push aborted.\n\n"
    exit 1
fi

printf "\n"

printf "Running tests:\n\n"
python manage.py test
if [ $? -ne 0 ]; then
    printf "Tests failed. Push aborted.\n\n"
    exit 1
fi

printf "\n"

printf "Testing requirements\n\n"
python -m pip install -r requirements.txt --require-virtualenv
if [ $? -ne 0 ]; then
    printf "Requirments not resolved. Push aborted.\n\n"
    exit 1
fi

printf "\n"

printf "Checks passed. Pushing...\n\n"
exit 0