#!/bin/bash
chmod +x ./wood

run="$1"

declare -A commands
commands["-a"]="source ../woodenv/bin/activate"
commands["-c"]="python manage.py check"
commands["-cd"]="python manage.py check --deploy"
commands["-d"]="docker run --rm -p 6379:6379 redis:latest"
commands["-m"]="python manage.py migrate"
commands["-mm"]="python manage.py makemigrations"
commands["-R"]="python -m gunicorn --reload --log-level debug wooden.asgi:application -k uvicorn.workers.UvicornWorker"
commands["-r"]="python -m daphne -b 0.0.0.0 -p 5006 wooden.asgi:application"
commands["-s"]="python manage.py shell"
commands["-st"]="python manage.py collectstatic --noinput"
commands["-t"]="python manage.py test"
commands["-req"]="python -m pip install -r requirements.txt --require-virtualenv"

if [ "$run" ]; then
    eval "${commands[$run]}"
fi
