# Generated by Django 5.0.1 on 2024-03-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('max_hits', models.IntegerField()),
                ('n_real', models.IntegerField()),
                ('n_bots', models.IntegerField()),
                ('started', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField()),
                ('creator', models.IntegerField()),
                ('winner', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('y', models.IntegerField()),
                ('x', models.IntegerField()),
                ('logged_in', models.BooleanField(default=True)),
                ('user', models.CharField(max_length=90)),
                ('game', models.IntegerField()),
            ],
        ),
    ]
