# Generated by Django 5.0.1 on 2024-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
