# Generated by Django 5.0.1 on 2024-03-04 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_ended_time_game_started_time_alter_game_ended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='x',
            new_name='c',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='y',
            new_name='r',
        ),
    ]
