# Generated by Django 5.0.1 on 2024-03-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_winner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='winners',
        ),
    ]
