# Generated by Django 5.0.1 on 2024-02-29 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('max_hits', models.IntegerField()),
                ('n_real', models.IntegerField()),
                ('n_bots', models.IntegerField()),
                ('started', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField()),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('y', models.IntegerField()),
                ('x', models.IntegerField()),
                ('current_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
