# Generated by Django 5.0.1 on 2024-03-01 05:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_game',
            new_name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='logged_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(default=datetime.datetime.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
