# Generated by Django 5.0.1 on 2024-03-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_player_game_alter_player_score_alter_player_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
