# Generated by Django 5.0.1 on 2024-03-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_current_game_player_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
