# Generated by Django 5.0.1 on 2024-03-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='data',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='game',
            name='initial_data',
            field=models.TextField(default='0'),
        ),
    ]
