# Generated by Django 5.0.1 on 2024-03-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_max_hits_alter_game_n_bots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ended_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='game',
            name='started_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
