# Generated by Django 5.0.1 on 2024-03-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_x_player_c_rename_y_player_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=200),
        ),
    ]
