# Generated by Django 5.0.1 on 2024-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_rename_winner_game_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
