# Generated by Django 5.0.1 on 2024-02-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.AddField(
            model_name='player',
            name='date_joined',
            field=models.DateField(auto_now=True),
        ),
    ]
