# Generated by Django 5.0.1 on 2024-02-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_player_email_player_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
