# Generated by Django 5.0.6 on 2024-06-03 02:23

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField(default=15)),
                ("initial_data", models.TextField(default="0")),
                ("data", models.TextField(default="0")),
                ("max_hits", models.IntegerField(default=3)),
                ("n_real", models.IntegerField(default=2)),
                ("n_bots", models.IntegerField(default=2)),
                ("started_time", models.DateTimeField(default=datetime.time(0, 0))),
                ("ended_time", models.DateTimeField(default=datetime.time(0, 0))),
                ("started", models.BooleanField(default=False)),
                ("ended", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_in", models.BooleanField(default=False)),
                ("score", models.IntegerField(default=0)),
                ("r", models.IntegerField(default=0)),
                ("c", models.IntegerField(default=0)),
                ("winner", models.BooleanField(default=False)),
                ("won", models.IntegerField(default=0)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="game.game"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
