# Generated by Django 5.0.6 on 2024-06-20 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_count_alter_game_max_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='no_of_players',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
