# Generated by Django 5.0.6 on 2024-06-20 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_game_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="max_hits",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
    ]
