# Generated by Django 5.0.6 on 2024-06-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_game_ended_time_alter_game_started_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="joined",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="present",
            field=models.BooleanField(default=False),
        ),
    ]
