# Generated by Django 5.0.6 on 2024-06-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_player_joined_player_present"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="data",
        ),
        migrations.RemoveField(
            model_name="game",
            name="initial_data",
        ),
        migrations.AddField(
            model_name="game",
            name="grid",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="game",
            name="initial_grid",
            field=models.TextField(default=""),
        ),
    ]
