# Generated by Django 5.0.6 on 2024-11-08 16:11

from django.db import migrations, models

import game.models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_remove_game_data_remove_game_initial_data_game_grid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="passcode",
            field=models.CharField(
                blank=True,
                max_length=5,
                null=True,
                validators=[game.models.validate_passcode_length],
            ),
        ),
    ]
