# Generated by Django 5.0.6 on 2024-11-08 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_game_passcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="count",
            new_name="no_of_players",
        ),
    ]
