# Generated by Django 5.1.3 on 2024-12-04 09:31

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_rename_count_game_no_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='passcode',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[game.models.validate_passcode_length, game.models.validate_passcode_availability]),
        ),
    ]
