# Generated by Django 5.1.10 on 2025-07-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_alter_game_passcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="max_hits",
            new_name="wood_strength",
        ),
    ]
