# Generated by Django 5.2.5 on 2026-03-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_rename_max_hits_game_wood_strength"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="temporary",
            field=models.BooleanField(default=False),
        ),
    ]
