# Generated by Django 6.0.3 on 2026-06-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_player_temporary"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
